# FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel
# FROM continuumio/anaconda3:latest
# Create user with LDAP credentials
ARG LDAP_USERNAME
ARG LDAP_UID
ARG LDAP_GROUPNAME
ARG LDAP_GID
RUN groupadd ${LDAP_GROUPNAME} --gid ${LDAP_GID}
RUN useradd -m -s /bin/bash -g ${LDAP_GROUPNAME} -u ${LDAP_UID} ${LDAP_USERNAME}
RUN mkdir /app /logs /data

ENV DEBIAN_FRONTEND=noninteractive
# Install system packages
SHELL ["/bin/bash", "-c"]
RUN apt-get update -y && apt-get install -yy --no-install-recommends \
    vim zsh tmux wget \
    curl htop jupyter python3 python3-pip libgl1-mesa-glx git sudo ssh git-lfs \
    libglib2.0-0 \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Give LDAP user permissions to conda directories
RUN chown -R ${LDAP_USERNAME}:${LDAP_GROUPNAME} /opt/conda
RUN chown -R ${LDAP_USERNAME}:${LDAP_GROUPNAME} /etc/profile.d
# Set your user as owner of the new copied files
RUN chown -R ${LDAP_USERNAME}:${LDAP_GROUPNAME} /home/${LDAP_USERNAME}
# Now switch to the LDAP user
USER ${LDAP_USERNAME}

# Ensure dotfiles exist with correct permissions
RUN touch /home/${LDAP_USERNAME}/.bashrc /home/${LDAP_USERNAME}/.zshrc && \
    chown ${LDAP_USERNAME}:${LDAP_GROUPNAME} /home/${LDAP_USERNAME}/.bashrc /home/${LDAP_USERNAME}/.zshrc && \
    chmod 644 /home/${LDAP_USERNAME}/.bashrc /home/${LDAP_USERNAME}/.zshrc

# Setup conda in user's shell config (using absolute paths)
# Do this BEFORE switching to the LDAP user
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/${LDAP_USERNAME}/.bashrc && \
    echo "conda activate base" >> /home/${LDAP_USERNAME}/.bashrc && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/${LDAP_USERNAME}/.zshrc && \
    echo "conda activate base" >> /home/${LDAP_USERNAME}/.zshrc

RUN mkdir -p /home/${LDAP_USERNAME}/Ti_workspace/sapiens

ENV PATH="/opt/conda/bin:${PATH}"

# Initialize conda for both bash and zsh (do this as root before user creation)
RUN conda init bash && conda init zsh

# Set up conda in shell
RUN ln -fs /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Install Python packages
RUN pip install -U openmim && \
    mim install mmengine mmcv mmpretrain && \
    pip install pandas future tensorboard gpustat
RUN pip install albumentations

# Switch to the new user and set home directory as working directory
# USER ${user_name}
ENV HOME=/home/${LDAP_USERNAME}
WORKDIR ${HOME}
# Install Oh My Zsh and plugins
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended \
&& git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions \
&& git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting \
&& sed -i 's/^plugins=(.*)$/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
RUN echo "export PATH=$PATH:/home/${LDAP_USERNAME}/.local/bin" >> /home/${LDAP_USERNAME}/.zshrc

# Set environment variables
# ENV SAPIENS_ROOT=/home/${LDAP_USERNAME}/Ti_workspace/sapiens
# ENV SAPIENS_LITE_ROOT=$SAPIENS_ROOT/lite

# WORKDIR /home/${LDAP_USERNAME}/Ti_workspace/sapiens

# Setup the conda environment for the LDAP user
# RUN mkdir -p /home/${LDAP_USERNAME}/.conda && \
#     chown -R ${LDAP_USERNAME}:${LDAP_GROUPNAME} /home/${LDAP_USERNAME} && \
#     echo 'export PATH="/opt/conda/bin:$PATH"' >> /home/${LDAP_USERNAME}/.zshrc && \
#     echo '. /opt/conda/etc/profile.d/conda.sh' >> /home/${LDAP_USERNAME}/.zshrc
# echo 'conda activate sapiens' >> /home/${LDAP_USERNAME}/.zshrc

# Setup zsh as the default shell
SHELL ["/bin/zsh", "-c"]
CMD ["zsh"]
# setup bash as the default shell
# SHELL ["/bin/bash", "-c"]
# CMD ["bash"]
