# FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel

# FROM continuumio/anaconda3:latest

ENV PATH="/opt/conda/bin:${PATH}"

# Install essential packages
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up conda in shell
RUN ln -fs /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Initialize conda for both bash and zsh (do this as root before user creation)
RUN conda init bash && conda init zsh

# Use the official Anaconda3 image from Docker Hub
# FROM continuumio/anaconda3:latest

#####################################
# RCP CaaS requirement (Storage)
#####################################
# Create your user inside the container.
# This block is needed to correctly map
# your EPFL user id inside the container.
# Without this mapping, you are not able
# to access files from the external storage.
ARG LDAP_USERNAME
ARG LDAP_UID
ARG LDAP_GROUPNAME
ARG LDAP_GID
RUN groupadd ${LDAP_GROUPNAME} --gid ${LDAP_GID}
RUN useradd -m -s /bin/bash -g ${LDAP_GROUPNAME} -u ${LDAP_UID} ${LDAP_USERNAME}

# ARG user_name=ti_wang
# ARG uid=1002
# ARG gid=1002
# ENV HOME=/root 
# WORKDIR /

# Copy your code inside the container
RUN mkdir -p /home/${LDAP_USERNAME}

ENV HOME=/home/${LDAP_USERNAME}
WORKDIR ${HOME}

# RUN git clone https://github.com/facebookresearch/sapiens.git
# Modify conda.sh to use the correct conda path and then execute it
# RUN cd sapiens/_install && \
    # sed -i "s|CONDA_BASE=\"/home/\${USER}/anaconda3\"|CONDA_BASE=\"/opt/conda\"|g" conda.sh && \
    # ./conda.sh

# Properly initialize and activate conda environment in a shell context
# SHELL ["/bin/bash", "--login", "-c"]
# Install additional packages in the sapiens environment
# RUN source ~/.bashrc && \
#     conda activate sapiens && \

RUN pip install -U openmim && \
    mim install mmengine && \
    mim install mmcv && \
    mim install mmpretrain
RUN pip install pandas
RUN pip install future tensorboard

ENV DEBIAN_FRONTEND=noninteractive
# Install system packages
SHELL ["/bin/bash", "-c"]
RUN apt-get update -y && apt-get install -yy --no-install-recommends \
    vim zsh tmux wget \
    curl htop jupyter python3 python3-pip libgl1-mesa-glx git sudo ssh git-lfs \
    libglib2.0-0 \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Create a non-root user
# RUN mkdir /app /logs /data
# RUN groupadd -g ${gid} ${user_name} \
#     && useradd -m -u ${uid} -g ${gid} ${user_name} \
#     && chown -R ${uid}:${gid} /home
    
# Switch to the new user and set home directory as working directory
# USER ${user_name}
# ENV HOME=/home/${user_name}

WORKDIR ${HOME}
# Install Oh My Zsh and plugins
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended \
&& git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions \
&& git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting \
&& sed -i 's/^plugins=(.*)$/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
RUN echo "export PATH=$PATH:/home/${LDAP_USERNAME}/.local/bin" >> /home/${LDAP_USERNAME}/.zshrc

# Set environment variables
ENV SAPIENS_ROOT=/home/${LDAP_USERNAME}/Ti_workspace/sapiens
ENV SAPIENS_LITE_ROOT=$SAPIENS_ROOT/lite

WORKDIR /home/${LDAP_USERNAME}/Ti_workspace/sapiens

# Setup the conda environment for the LDAP user
RUN mkdir -p /home/${LDAP_USERNAME}/.conda && \
    chown -R ${LDAP_USERNAME}:${LDAP_GROUPNAME} /home/${LDAP_USERNAME} && \
    echo 'export PATH="/opt/conda/bin:$PATH"' >> /home/${LDAP_USERNAME}/.zshrc && \
    echo '. /opt/conda/etc/profile.d/conda.sh' >> /home/${LDAP_USERNAME}/.zshrc
# echo 'conda activate sapiens' >> /home/${LDAP_USERNAME}/.zshrc

# Now switch to the LDAP user
USER ${LDAP_USERNAME}
USER root
CMD ["zsh"]
SHELL ["/bin/zsh", "-c"]